### ISSUE TITLE
ToDo-o-meter

### ISSUE THREAD

**Issue by ghost** [NoitosferaFansub/NoitosNext#5]
- [ ] Arrumar o episodeinfo para que o usuario não tenha como abrir multiplas abas ao mesmo tempo.

- [x] Mini-detalhes graficos (eu tomo conta disso mais tarde)

- [ ] Arrumar certas coisas para que fique texto-puro ao invez de PNG.

- [ ] Subtitulo ao dar hover nas categorias principais
![image](https://cloud.githubusercontent.com/assets/18196173/26324761/879c9cee-3f0a-11e7-8258-21b0ca67d9c8.png)

- [ ] Créditos no final da página

- [x] Adotar o /google/web-starter-kit. 
- [ ] Issue #3  - admMENU
- [x] Issue #7 - Listagem dinâmica dos episódios da temporada

- [ ] Issue #4 - Grafico de Progresso

**Comment by gustarrini** [comment]
[ATUALIZADO 22.05.17]
